### ISSUE TITLE
varfish_annotator - get genome from config

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#113]
**Issue**
Currently `varfish_annotator/annotate_sv` wrapper has 'GRCh37' hardcoded for `varfish-annotator --release`.

**Expected behavior**
The genome version should come from the config.

**Additional context**
Relevant code:  https://github.com/bihealth/snappy-pipeline/blob/master/snappy_wrappers/wrappers/varfish_annotator/annotate_sv/wrapper.py#L92

**Comment by eudesbarbosa** [comment]
Moving to higher priority...

Impacting CADS tests:
```
INFO: Genome looks like GRCh38 (sequence only; regardless of 'chr' prefix).
Problem with VCF compatibility: VCF file looks like hg38 by chr1 length you required GRCh37
com.github.bihealth.varfish_annotator.annotate.IncompatibleVcfException: VCF file looks like hg38 by chr1 length you required GRCh37
        at com.github.bihealth.varfish_annotator.annotate.VcfCompatibilityChecker.check(VcfCompatibilityChecker.java:56)
        at com.github.bihealth.varfish_annotator.annotate.AnnotateVcf.run(AnnotateVcf.java:152)
        at com.github.bihealth.varfish_annotator.VarfishAnnotatorCli.main(VarfishAnnotatorCli.java:57)
```
