### ISSUE TITLE
snappy packages not found by parallel wrappers

### ISSUE THREAD

**Issue by ericblanc20** [bihealth/snappy-pipeline#200]
**Describe the bug**

The `mutect2` parallel wrapper fails for the `run` action because the `snappy` package in not found in the parallel wrapper environment. 

The error is:

```
09-10 09:36 snakemake.logging WARNING  Activating conda environment: .snakemake/conda/4b69861fa5a6588566d508436fb61e80
Traceback (most recent call last):
  File "/fast/work/groups/cubi/projects/2022-08-25_Molecular_Profiling_PDO_Tinhofer/pipeline/standard/somatic_variant_calling/.snakemake/scripts/tmpsz1par0l.wrapper.py", line 8, in <module>
    from parallel_mutect2 import ParallelMutect2Wrapper
  File "/data/gpfs-1/work/users/blance_c/Development/snappies/master/snappy_wrappers/wrappers/mutect2_par/run/parallel_mutect2.py", line 11, in <module>
    from snappy_wrappers.resource_usage import ResourceUsage  # noqa: E402
ModuleNotFoundError: No module named 'snappy_wrappers'
```

**To Reproduce**
1. activate the snappy envrionment
2. in the `somatic_variant_calling` step, start the step with `snappy-snake`
3. The error occurs for all `run` sub-steps

**Expected behavior**
The `run` sub-steps should complete without error.

**Additional context**

**`snappy` conda environment**
```
# packages in environment at /fast/work/users/blance_c/miniconda3/envs/snappy:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
abseil-cpp                20211102.0           h27087fc_1    conda-forge
aioeasywebdav             2.4.0           py39hf3d152e_1001    conda-forge
aiohttp                   3.8.1            py39hb9d737c_1    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
alabaster                 0.7.12                   pypi_0    pypi
alsa-lib                  1.2.6.1              h7f98852_0    conda-forge
altamisa                  0.2.9              pyhdfd78af_0    bioconda
amply                     0.1.5              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
astroid                   2.4.1                    pypi_0    pypi
asttokens                 2.0.5                    pypi_0    pypi
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attmap                    0.13.2             pyhd8ed1ab_0    conda-forge
attr                      2.5.1                h166bdaf_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
babel                     2.10.3                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcftools                  1.15.1               h0ea216a_0    bioconda
bcrypt                    3.2.2            py39hb9d737c_0    conda-forge
biomedsheets              0.11.4                   pypi_0    pypi
black                     20.8b1                   pypi_0    pypi
boto3                     1.24.27            pyhd8ed1ab_0    conda-forge
botocore                  1.27.27            pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h166bdaf_7    conda-forge
brotli-bin                1.0.9                h166bdaf_7    conda-forge
brotlipy                  0.7.0           py39hb9d737c_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
cachetools                5.0.0              pyhd8ed1ab_0    conda-forge
cattrs                    1.10.0                   pypi_0    pypi
certifi                   2022.6.15        py39hf3d152e_0    conda-forge
cffi                      1.15.1           py39he91dace_0    conda-forge
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
click                     7.1.2                    pypi_0    pypi
coin-or-cbc               2.10.8               h3786ebc_0    conda-forge
coin-or-cgl               0.60.6               h6f57e76_1    conda-forge
coin-or-clp               1.17.7               hc56784d_1    conda-forge
coin-or-osi               0.108.7              h2720bb7_1    conda-forge
coin-or-utils             2.11.6               h202d8b1_1    conda-forge
coincbc                   2.10.8            0_metapackage    conda-forge
configargparse            1.5.3              pyhd8ed1ab_0    conda-forge
connection_pool           0.0.3              pyhd3deb0d_0    conda-forge
coverage                  6.4.2                    pypi_0    pypi
coveralls                 3.3.1                    pypi_0    pypi
cryptography              37.0.4           py39hd97740a_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
datrie                    0.8.2            py39h3811e60_3    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
dodgy                     0.2.1                    pypi_0    pypi
dpath                     2.0.6            py39hf3d152e_1    conda-forge
dropbox                   11.32.0            pyhd8ed1ab_0    conda-forge
executing                 0.8.3                    pypi_0    pypi
expat                     2.4.8                h27087fc_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
fftw                      3.3.10          nompi_h77c792f_102    conda-forge
filechunkio               1.8                        py_2    conda-forge
filelock                  3.7.1              pyhd8ed1ab_0    conda-forge
flake8                    3.8.4                    pypi_0    pypi
flake8-import-order       0.18.1                   pypi_0    pypi
flake8-polyfill           1.0.2                    pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.34.4           py39hb9d737c_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
frozenlist                1.3.0            py39hb9d737c_1    conda-forge
ftputil                   5.0.4              pyhd8ed1ab_0    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
git-lfs                   3.2.0                ha770c72_0    conda-forge
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.27             pyhd8ed1ab_0    conda-forge
glib                      2.72.1               h6239696_0    conda-forge
glib-tools                2.72.1               h6239696_0    conda-forge
google-api-core           2.8.2              pyhd8ed1ab_0    conda-forge
google-api-python-client  2.52.0             pyhd8ed1ab_0    conda-forge
google-auth               2.9.0              pyh6c4a22f_0    conda-forge
google-auth-httplib2      0.1.0              pyhd8ed1ab_1    conda-forge
google-cloud-core         2.3.1              pyhd8ed1ab_0    conda-forge
google-cloud-storage      2.4.0              pyh6c4a22f_0    conda-forge
google-crc32c             1.1.2            py39h8db88ab_3    conda-forge
google-resumable-media    2.3.3              pyhd8ed1ab_0    conda-forge
googleapis-common-protos  1.56.3           py39hf3d152e_0    conda-forge
grpc-cpp                  1.47.0               hbd84cd8_1    conda-forge
grpcio                    1.47.0           py39h7ad10b3_1    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gst-plugins-base          1.20.3               hf6a322e_0    conda-forge
gstreamer                 1.20.3               hd4edc92_0    conda-forge
htslib                    1.15.1               h9753748_0    bioconda
httplib2                  0.20.4             pyhd8ed1ab_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        1.7.0                    pypi_0    pypi
importlib_resources       5.8.0              pyhd8ed1ab_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipython                   8.4.0                    pypi_0    pypi
isort                     4.3.21                   pypi_0    pypi
jack                      1.9.18            h8c3723f_1002    conda-forge
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
jsonpath-rw               1.4.0                    pypi_0    pypi
jsonschema                4.4.0                    pypi_0    pypi
jupyter_core              4.10.0           py39hf3d152e_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.3            py39hf939315_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lazy-object-proxy         1.4.3                    pypi_0    pypi
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           15_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcap                    2.64                 ha37c62d_0    conda-forge
libcblas                  3.9.0           15_linux64_openblas    conda-forge
libclang                  14.0.6          default_h2e3cab8_0    conda-forge
libclang13                14.0.6          default_h3a83d3e_0    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcups                   2.3.3                hf5a7f15_1    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libdb                     6.2.32               he1b5a44_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.3.4                h27087fc_0    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.72.1               h2d90d5f_0    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           15_linux64_openblas    conda-forge
liblapacke                3.9.0           15_linux64_openblas    conda-forge
libllvm14                 14.0.6               he0ac6c6_0    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h753d276_3    conda-forge
libpq                     14.4                 hd77ab85_0    conda-forge
libprotobuf               3.20.1               h6239696_0    conda-forge
libsndfile                1.0.31               h9c3ff4c_1    conda-forge
libsodium                 1.0.18               h516909a_1    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                h0fcbabc_0    conda-forge
libtool                   2.4.6             h9c3ff4c_1008    conda-forge
libudev1                  249                  h166bdaf_4    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libvorbis                 1.3.7                he1b5a44_0    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.14               h22db469_3    conda-forge
libzlib                   1.2.12               h166bdaf_1    conda-forge
logmuse                   0.2.6              pyh8c360ce_0    conda-forge
logzero                   1.7.0                    pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markupsafe                2.1.1            py39hb9d737c_1    conda-forge
matplotlib                3.5.2            py39hf3d152e_0    conda-forge
matplotlib-base           3.5.2            py39h700656a_0    conda-forge
matplotlib-inline         0.1.3                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
monotonic                 1.6                      pypi_0    pypi
multidict                 6.0.2            py39hb9d737c_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy-extensions           0.4.3                    pypi_0    pypi
mysql-common              8.0.29               haf5c9bc_1    conda-forge
mysql-libs                8.0.29               h28c427c_1    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.78                 h2350873_0    conda-forge
numpy                     1.23.1           py39hba7629e_0    conda-forge
oauth2client              4.1.3                      py_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3            py39h1832856_0    conda-forge
paramiko                  2.11.0             pyhd8ed1ab_0    conda-forge
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.9.0                    pypi_0    pypi
pcre                      8.45                 h9c3ff4c_0    conda-forge
pep8-naming               0.10.0                   pypi_0    pypi
peppy                     0.31.2             pyhd8ed1ab_2    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0            py39hae2aec6_0    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
plac                      1.3.5              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py39hf3d152e_3    conda-forge
ply                       3.11                       py_1    conda-forge
poetry-semver             0.1.0                    pypi_0    pypi
portaudio                 19.6.0               h57a0ea0_5    conda-forge
prettytable               3.3.0              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30                   pypi_0    pypi
prospector                1.3.1                    pypi_0    pypi
protobuf                  3.20.1           py39h5a03fae_0    conda-forge
psutil                    5.9.1            py39hb9d737c_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pulp                      2.6.0            py39hf3d152e_1    conda-forge
pulseaudio                14.0                 h7f54b18_8    conda-forge
pure-eval                 0.2.2                    pypi_0    pypi
py                        1.11.0             pyh6c4a22f_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycodestyle               2.6.0                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydocstyle                6.1.1                    pypi_0    pypi
pyfakefs                  4.5.6                    pypi_0    pypi
pyflakes                  2.2.0                    pypi_0    pypi
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pylint                    2.5.3                    pypi_0    pypi
pylint-celery             0.3                      pypi_0    pypi
pylint-django             2.1.0                    pypi_0    pypi
pylint-flask              0.6                      pypi_0    pypi
pylint-plugin-utils       0.7                      pypi_0    pypi
pynacl                    1.5.0            py39hb9d737c_1    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py39h18e9c17_0    conda-forge
pyqt5-sip                 12.11.0          py39h5a03fae_0    conda-forge
pyrsistent                0.18.1           py39hb9d737c_1    conda-forge
pysam                     0.19.1           py39h5030a8b_0    bioconda
pysftp                    0.2.9                      py_1    conda-forge
pysocks                   1.7.1            py39hf3d152e_5    conda-forge
pytabix                   0.1              py39h2add14b_2    bioconda
pytest                    7.1.2            py39hf3d152e_0    conda-forge
pytest-cov                3.0.0                    pypi_0    pypi
pytest-flake8             1.1.0                    pypi_0    pypi
pytest-mock               3.8.2                    pypi_0    pypi
pytest-pdb                0.3.1                    pypi_0    pypi
pytest-sugar              0.9.5                    pypi_0    pypi
python                    3.9.13          h9a8a25e_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.15.3             pyhd8ed1ab_0    conda-forge
python-irodsclient        1.1.4              pyhd8ed1ab_0    conda-forge
python-levenshtein        0.12.2                   pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39hb9d737c_4    conda-forge
qt-main                   5.15.4               ha5833f6_2    conda-forge
ratelimiter               1.2.0                   py_1002    conda-forge
re2                       2022.06.01           h27087fc_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
regex                     2022.7.9                 pypi_0    pypi
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
requests-file             1.5.1                    pypi_0    pypi
requirements-detector     1.0.3                    pypi_0    pypi
retry                     0.9.2                      py_0    conda-forge
rsa                       4.8                pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21          py39hb9d737c_1    conda-forge
ruamel.yaml.clib          0.2.6            py39hb9d737c_1    conda-forge
s3transfer                0.6.0              pyhd8ed1ab_0    conda-forge
setoptconf                0.3.0                    pypi_0    pypi
setuptools                63.1.0           py39hf3d152e_0    conda-forge
simplejson                3.17.6                   pypi_0    pypi
sip                       6.6.2            py39h5a03fae_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slacker                   0.14.0                     py_0    conda-forge
smart_open                6.0.0              pyhd8ed1ab_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snakefmt                  0.3.1                    pypi_0    pypi
snakemake                 7.8.5                hdfd78af_0    bioconda
snakemake-minimal         7.8.5              pyhdfd78af_0    bioconda
snappy-pipeline           0+untagged.68.ge260f7f           dev_0    <develop>
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    4.3.2                    pypi_0    pypi
sphinx-rtd-theme          1.0.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.39.0               h4ff8645_0    conda-forge
stack-data                0.3.0                    pypi_0    pypi
stone                     3.3.1              pyhd8ed1ab_0    conda-forge
stopit                    1.1.2                      py_0    conda-forge
tabulate                  0.8.10             pyhd8ed1ab_0    conda-forge
termcolor                 1.1.0              pyhd8ed1ab_3    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toposort                  1.7                pyhd8ed1ab_0    conda-forge
tornado                   6.2              py39hb9d737c_0    conda-forge
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.4                    pypi_0    pypi
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ubiquerg                  0.6.1              pyh9f0ad1d_0    conda-forge
unicodedata2              14.0.0           py39hb9d737c_1    conda-forge
uritemplate               4.1.1              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.10            pyhd8ed1ab_0    conda-forge
varfish-cli               0.3.4                    pypi_0    pypi
vcfpy                     0.13.4             pyhdfd78af_0    bioconda
veracitools               0.1.3                      py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.14.1           py39hb9d737c_0    conda-forge
xcb-util                  0.4.0                h516909a_0    conda-forge
xcb-util-image            0.4.0                h166bdaf_0    conda-forge
xcb-util-keysyms          0.4.0                h516909a_0    conda-forge
xcb-util-renderutil       0.3.9                h166bdaf_0    conda-forge
xcb-util-wm               0.4.1                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.7.2            py39hb9d737c_2    conda-forge
yte                       1.5.1            py39hf3d152e_0    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_1    conda-forge
zstd                      1.5.2                h8a70e8d_2    conda-forge
```

**Wrapper environment**

```
# packages in environment at /fast/work/groups/cubi/projects/2022-08-25_Molecular_Profiling_PDO_Tinhofer/pipeline/standard/somatic_variant_calling/.snakemake/conda/4b69861fa5a6588566d508436fb61e80:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.6.1              h7f98852_0    conda-forge
amply                     0.1.5              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
bcftools                  1.15.1               h0ea216a_0    bioconda
brotlipy                  0.7.0                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15.1          ha878542_0    conda-forge
cairo                     1.16.0            ha61ee94_1013    conda-forge
certifi                   2022.6.15.1        pyhd8ed1ab_0    conda-forge
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
coin-or-cbc               2.10.8               h3786ebc_0    conda-forge
coin-or-cgl               0.60.6               h6f57e76_2    conda-forge
coin-or-clp               1.17.7               hc56784d_2    conda-forge
coin-or-osi               0.108.7              h2720bb7_2    conda-forge
coin-or-utils             2.11.6               h202d8b1_2    conda-forge
coincbc                   2.10.8            0_metapackage    conda-forge
configargparse            1.5.3              pyhd8ed1ab_0    conda-forge
connection_pool           0.0.3              pyhd3deb0d_0    conda-forge
cryptography              37.0.4                   pypi_0    pypi
datrie                    0.8.2                    pypi_0    pypi
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
docutils                  0.19                     pypi_0    pypi
dpath                     2.0.6                    pypi_0    pypi
expat                     2.4.8                h27087fc_0    conda-forge
filelock                  3.8.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hca18f0e_0    conda-forge
gatk4                     4.2.6.1          py36hdfd78af_1    bioconda
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.27             pyhd8ed1ab_0    conda-forge
graphite2                 1.3.13            he1b5a44_1001    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
harfbuzz                  5.1.0                hf9f4e7c_0    conda-forge
htslib                    1.15.1               h9753748_0    bioconda
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4                   pypi_0    pypi
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
jsonschema                4.16.0             pyhd8ed1ab_0    conda-forge
jupyter-core              4.11.1                   pypi_0    pypi
jupyter_core              4.11.1          py310hff52083_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcups                   2.3.3                h3e49a29_2    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.72.1               h2d90d5f_0    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
liblapacke                3.9.0           16_linux64_openblas    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.37               h753d276_4    conda-forge
libsqlite                 3.39.3               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                h0fcbabc_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
markupsafe                2.1.1                    pypi_0    pypi
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openjdk                   11.0.15              h1e1ecb3_1    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
plac                      1.3.5              pyhd8ed1ab_0    conda-forge
psutil                    5.9.2                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pulp                      2.6.0                    pypi_0    pypi
py                        1.11.0             pyh6c4a22f_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.10.6          h582c2e5_0_cpython    conda-forge
python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pyyaml                    6.0                      pypi_0    pypi
ratelimiter               1.2.0                   py_1002    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
retry                     0.9.2                      py_0    conda-forge
setuptools                65.3.0                   pypi_0    pypi
smart_open                6.1.0              pyhd8ed1ab_1    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snakemake-minimal         7.14.0             pyhdfd78af_0    bioconda
stopit                    1.1.2                      py_0    conda-forge
tabulate                  0.8.10             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toposort                  1.7                pyhd8ed1ab_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.14.1                   pypi_0    pypi
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxtst              1.2.3             h7f98852_1002    conda-forge
xorg-recordproto          1.14.2            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yte                       1.5.1                    pypi_0    pypi
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_2    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

**Comment by holtgrewe** [comment]
This is caused by me removing the `sys.path` modification in wrappers earlier. Will fix.

**Comment by holtgrewe** [comment]
Can you try whether the branch `200-snappy-packages-not-found-by-parallel-wrappers` fixes the issue (it should)?
