### ISSUE TITLE
Encoding issue - ASCII

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#65]
**Description**
NGS mapping workflow crashes during `plot-bamstats` execution due to Click encoding configurations:
```
...
+ plot-bamstats -p <PATH>/scratch/tmp/med0750/20210505/tmp.Dd77oKxX1l/bamstats.d/ work/bwa.<SAMPLE>-N1-DNA1-WES1/report/bam_qc/bwa.<SAMPLE>-N1-DNA1-WES1.bam.bamstats.txt
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
+ inline-html --in-file <PATH>/scratch/tmp/med0750/20210505/tmp.Dd77oKxX1l/bamstats.d/index.html --out-file work/bwa.<SAMPLE>-N1-DNA1-WES1/report/bam_qc/bwa<SAMPLE>-N1-DNA1-WES1.bam.bamstats.html
Traceback (most recent call last):
  File "<PROJECT_PATH>/GRCh37/ngs_mapping/.snakemake/conda/0453b148/bin/inline-html", line 10, in <module>
    sys.exit(inline_resources())
  File "<PROJECT_PATH>/GRCh37/ngs_mapping/.snakemake/conda/0453b148/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "<PROJECT_PATH>/GRCh37/ngs_mapping/.snakemake/conda/0453b148/lib/python3.6/site-packages/click/core.py", line 760, in main
    _verify_python3_env()
  File "<PROJECT_PATH>/GRCh37/ngs_mapping/.snakemake/conda/0453b148/lib/python3.6/site-packages/click/_unicodefun.py", line 130, in _verify_python3_env
    " mitigation steps.{}".format(extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system lists a couple of UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: 
...
```

**To Reproduce**
1. Ask me for project and batch associated with error.
2. Execute germline analysis. Problem should emerge after `cubi-tk snappy kickoff`.
3. Check latest logs in `ngs_mapping/slurm_log/`.
4. See error.

**Additional context**
Possible solution in https://click.palletsprojects.com/python3/ 
Add following lines to `bwa` wrapper.
```
export LC_ALL=de_DE.utf-8
export LANG=de_DE.utf-8
```

**Comment by holtgrewe** [comment]
I'd always go for `LC_ALL=C` to force C encoding which always work.

**Comment by eudesbarbosa** [comment]
Problem solved on the user level. 
In `.bashrc`:
```
export LC_ALL=C
export LANG=en_US
```
