### ISSUE TITLE
Pin bcftool and related packages version

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#84]
**Issue**
Version 1.13 of `bcftools` incompatible with VCF structure, it fails to read header with meta information during `variant_calling` step:
```
++ mktemp -d
+ export TMPDIR=/path/to/scratch/tmp/med0103/20210823/tmp.3HK7GTb1nD
+ TMPDIR=/path/to/scratch/tmp/med0103/20210823/tmp.3HK7GTb1nD
+ trap 'rm -rf /path/to/scratch/tmp/med0103/20210823/tmp.3HK7GTb1nD' EXIT
+ [[ -n work/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1/log/bcftools_stats/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1.<SAMPLE_ID>-N1-DNA1-WES1.log ]]
++ set +e
++ tty
++ set -e
+ [[ not a tty != '' ]]
+ rm -f work/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1/log/bcftools_stats/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1.<SAMPLE_ID>-N1-DNA1-WES1.log
++ dirname work/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1/log/bcftools_stats/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1.<SAMPLE_ID>-N1-DNA1-WES1.log
+ mkdir -p work/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1/log/bcftools_stats
+ exec
++ tee -a work/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1/log/bcftools_stats/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1.<SAMPLE_ID>-N1-DNA1-WES1.log
+ bcftools stats --split-by-ID -s <SAMPLE_ID>-N1-DNA1-WES1 work/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1/out/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1.vcf.gz
++ dirname work/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1/report/bcftools_stats/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1.<SAMPLE_ID>-N1-DNA1-WES1.txt
++ basename work/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1/report/bcftools_stats/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1.<SAMPLE_ID>-N1-DNA1-WES1.txt .txt
Could not parse the header line: "##META=<ID=Sex,Type=String,Number=1,Values=[Unknown, Male, Female]>"
Warning: The sample "<SAMPLE_ID>-N1-DNA1-WES1" was not found in work/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1/out/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1.vcf.gz, skipping
No sample columns in work/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1/out/bwa.gatk_hc.<SAMPLE_ID>-N1-DNA1-WES1.vcf.gz
+ rm -rf /path/to/scratch/tmp/med0103/20210823/tmp.3HK7GTb1nD
Traceback (most recent call last):
  File "/path/to/project/GRCh37/variant_calling/.snakemake/scripts/tmp7elv06rn.wrapper.py", line 13, in <module>
    shell(
  File "/path/to/lib/python3.8/site-packages/snakemake/shell.py", line 213, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '
```

**Suggestion**
Fix version of `bcftools` and related packages to 1.12 in wrappers used in `variant_calling` step:
* snappy_wrappers/wrappers/gatk_ug_par/environment.yaml
* snappy_wrappers/wrappers/jannovar/environment.yaml
_Note_: `variant_calling_bcftools_stats_report` uses an old version and probably shouldn't be changed.

<img width="307" alt="dag_variant_calling" src="https://user-images.githubusercontent.com/22077515/130935561-86449e35-7997-407d-8df2-218f72a66ad8.PNG">

**Comment by eudesbarbosa** [comment]
Temporary solution to continue with production. 
VCF header probably needs to be changed: `ped_to_vcf_header.py`: [L29](https://github.com/bihealth/snappy-pipeline/blob/master/snappy_wrappers/tools/ped_to_vcf_header.py#L29)
Guidelines: https://samtools.github.io/hts-specs/VCFv4.3.pdf
